Update patch set 3
Patch Set 3:

This caused following error to appear while CX2 is loading:

Uncaught Error: inheritClass: Origin is not a function (actually undefined)
    at Object.oo.inheritClass (oojs.jquery.js?76d02:83)
    at ve.ui.MWLinkInspectorTool.js?e6358:35

Patch-set: 3