Revert "[BREAKING CHANGE] Do not cache document model data in DM selections"
This reverts commit ccb4de82c61b58e5f2af081c9758d28fff9c0d82.

Reason for revert: `Uncaught TypeError: startingSelection.getDocument is not a function` from ve.ui.DesktopContext.prototype.updateDimensions on every page.

Change-Id: I066c97fa77b056b08dedc904c36a798d1c42e14a
(cherry picked from commit ed181bdea5d9950d94a2e0949037646dacc4d3c2)